---
book_repo: cloudfoundry/docs-book-cloudfoundry

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true
elastic_search: true

public_host: docs.cloudfoundry.org

sections:
- repository:
    name: cloudfoundry/docs-cf-cli
    ref: master
  directory: cf-cli
  subnav_template: cf-subnav.erb